### ISSUE TITLE
Wiki Pages

### ISSUE THREAD

**Issue by rkoron007** [jingxia1219/Instagram-Clone#2]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments:

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments:

---

# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
## Comments:

---

# Routes

- [x] Routes accurately reflect MVPs and Component Hierarchy
- [x] Covers the frontend functionality of the site through routes that match to the wireframes
- [x] Contains the following sections: HTML, API Endpoints(Backend), and Frontend Routes
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint bc that info comes through the post show
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments:

---

# Sample State
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema (Ex: if you create a `imgUrl` key in the state, make sure your database also has a column that contains an `img_url`)
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice
    
## Comments:

---

**Comment by rkoron007** [comment]
`MVP List`: 
- love the switch out of comments for search! I think search is way cooler.
- I'd say posts would probably be your CRUD feature - users should be able to create, update, delete and edit posts. So just put a note next to it saying its CRUD.

**Comment by rkoron007** [comment]
`Database Schema`: 
- You will not need any avatar_urls because you will be using AWS which will give you an association to use. 
- Will you be doing Comments? If so I'd consider that as one of your MVP's and consider Search a bonus. 
- Can you comment on other comments? If so you'd probably want a `parent_comment_id`. 
- It seems like your `Followings` table does exactly what your `followees` and `followers` tables are doing. I think you just need `Followings` in that case. 
- Password_digest and session_token should both be  unique and session_token should be indexed.

**Comment by rkoron007** [comment]
`Routes`:
`Backend`:
- `GET/api/users` - could return the current user's page, but if you wanted to look at another user's profile you'd probably need to get an id `GET/api/users/:user_id`
- `posts`: 
- should have a `patch` route to update a post
`FrontEnd`:
- Check spelling for `Postposts/:postId/edit`
- Separate the `Post Show` route from the `Post Edit route`(/posts/:postId vs Postposts/:postId/edit) as two different routes.

**Comment by rkoron007** [comment]
`Sample State`:
- If you are going to have comments make sure they are under entities in your state shape. 
-`followings` should also be under entities in your state shape. (and you can remove followees, and followers)
- for Errors you'll probably have different errors for different things as you make them. For example you'd have posterrors for when a post wasn't made successfully and you wanted to render errors to the user.

**Comment by jingxia1219** [comment]
I fixed everything according to the comment, my pages are ready for review.

**Comment by rkoron007** [comment]
`MVP List`:
- I think you Styling got a little broken- try adding another line break by 5. Likes.

`Database Schema`:
- you won't have `image_url`'s for your posts either because of AWS carrying around the association for you. 
- `parent_comment_id`- watch the spelling of foreign in your table.

`Routes`:
- make sure you finish the sentence for - `GET/api/users/:user_id`

 
Once you fix these things you are good to start your fullstack. :)
Looks awesome!!!

**Comment by jingxia1219** [comment]
HI, Rose.
I just fixed those.

**Comment by rkoron007** [comment]
`Routes`: make sure you tell what GET/api/users/:user_id would return (a user's posts? a user's follows? A user's information?)
